/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SepatuDAO;
import controller.Sepatu_SupplierDAO;
import controller.SupplierDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Sepatu;
import model.Sepatu_Supplier;
import model.Supplier;

/**
 *
 * @author lexs
 */
public class FormTokoSepatu extends javax.swing.JFrame {

    /**
     * Creates new form FormTokoSepatu
     */
    
    SupplierDAO supDAO;
    SepatuDAO sptDAO;
    Sepatu_SupplierDAO ssDAO;
    JPanel productPanel;
    
    public FormTokoSepatu() {
        initComponents();
        URL iconURL = getClass().getResource("/Images/house.png");
        ImageIcon icon = new ImageIcon(iconURL);
        setIconImage(icon.getImage());
        
        productPanel = jPanel3;
        jTabbedPane1.remove(jPanel3);
        supDAO = new SupplierDAO();
        sptDAO = new SepatuDAO();
        ssDAO = new Sepatu_SupplierDAO();
        LihatDataSupplier();
        LihatDataSepatu();
    }
    
    public void LihatDataSupplier(){
        Object[][] dataSupplier = new Object[supDAO.GetAllSupplier().size()][2];
        int i = 0;
        for(Supplier sp:supDAO.GetAllSupplier()){
            dataSupplier[i][0] = sp.getId_supplier();
            dataSupplier[i][1] = sp.getNama_supplier();
            i++;
        }
        tbSupplier.setModel(new DefaultTableModel(dataSupplier, new String[]{"ID", "Nama Supplier"}));
        if(tbSupplier.getSelectedRowCount() > 0){
            menuUpdate.setEnabled(true);
            menuDelete.setEnabled(true);
            menuProduct.setEnabled(true);
        } else{
            menuUpdate.setEnabled(false);
            menuDelete.setEnabled(false);
            menuProduct.setEnabled(false);
        }
    }
    
    public void LihatDataSepatu(){
        Object[][] dataSepatu = new Object[sptDAO.GetAllSepatu().size()][3];
        int i = 0;
        for(Sepatu sp:sptDAO.GetAllSepatu()){
            dataSepatu[i][0] = sp.getId_sepatu();
            dataSepatu[i][1] = sp.getNama_sepatu();
            dataSepatu[i][2] = sp.getJenis();
            i++;
        }
        tbSepatu.setModel(new DefaultTableModel(dataSepatu, new String[]{"ID", "Nama Sepatu", "Jenis"}));
        if(tbSepatu.getSelectedRowCount() > 0){
            menuUpdate.setEnabled(true);
            menuDelete.setEnabled(true);
            menuProduct.setEnabled(true);
            menuAddProduct.setEnabled(true);
        } else{
            menuUpdate.setEnabled(false);
            menuDelete.setEnabled(false);
            menuProduct.setEnabled(false);
            menuAddProduct.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupTable = new javax.swing.JPopupMenu();
        menuUpdate = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenuItem();
        menuProduct = new javax.swing.JMenuItem();
        menuAddProduct = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSupplier = new javax.swing.JTable();
        btnSupplierLihat = new javax.swing.JButton();
        btnSupplierInsert = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbSepatu = new javax.swing.JTable();
        btnSepatuLihat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbProduct = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbSupplier = new javax.swing.JLabel();

        menuUpdate.setText("Update");
        menuUpdate.setEnabled(false);
        menuUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateActionPerformed(evt);
            }
        });
        popupTable.add(menuUpdate);

        menuDelete.setText("Delete");
        menuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeleteActionPerformed(evt);
            }
        });
        popupTable.add(menuDelete);

        menuProduct.setText("Daftar Product");
        menuProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductActionPerformed(evt);
            }
        });
        popupTable.add(menuProduct);

        menuAddProduct.setText("Add Product");
        menuAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddProductActionPerformed(evt);
            }
        });
        popupTable.add(menuAddProduct);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daftar Sepatu");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        tbSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Supplier"
            }
        ));
        tbSupplier.setComponentPopupMenu(popupTable);
        tbSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSupplierMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbSupplierMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbSupplierMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbSupplier);

        btnSupplierLihat.setText("Refresh");
        btnSupplierLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierLihatActionPerformed(evt);
            }
        });

        btnSupplierInsert.setText("Insert");
        btnSupplierInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSupplierLihat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupplierInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupplierLihat)
                    .addComponent(btnSupplierInsert))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Supplier", jPanel1);

        tbSepatu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Sepatu", "Jenis"
            }
        ));
        tbSepatu.setComponentPopupMenu(popupTable);
        tbSepatu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbSepatuMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tbSepatu);

        btnSepatuLihat.setText("Refresh");
        btnSepatuLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSepatuLihatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSepatuLihat)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSepatuLihat)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sepatu", jPanel2);

        tbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Sepatu"
            }
        ));
        jScrollPane4.setViewportView(tbProduct);

        jLabel1.setText("Supplier");

        lbSupplier.setText("---");
        lbSupplier.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbSupplier))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Supplier Product", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-362)/2, 416, 362);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupplierLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierLihatActionPerformed
        LihatDataSupplier();
    }//GEN-LAST:event_btnSupplierLihatActionPerformed

    private void btnSupplierInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierInsertActionPerformed
        FormSupplier fIS = new FormSupplier(supDAO, "", this);
        fIS.setTitle("Insert Supplier");
        fIS.setVisible(true);
        fIS.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnSupplierInsertActionPerformed

    private void tbSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSupplierMouseClicked
        
    }//GEN-LAST:event_tbSupplierMouseClicked

    private void btnSepatuLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSepatuLihatActionPerformed
        LihatDataSepatu();
    }//GEN-LAST:event_btnSepatuLihatActionPerformed

    private void tbSupplierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSupplierMouseReleased
        
    }//GEN-LAST:event_tbSupplierMouseReleased

    private void tbSupplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSupplierMousePressed
        if(tbSupplier.getSelectedRowCount() > 0){
            menuUpdate.setEnabled(true);
            menuDelete.setEnabled(true);
            menuProduct.setEnabled(true);
            menuAddProduct.setEnabled(true);
        } else{
            menuUpdate.setEnabled(false);
            menuDelete.setEnabled(false);
            menuProduct.setEnabled(false);
            menuAddProduct.setEnabled(false);
        }
        menuProduct.setVisible(true);
        menuAddProduct.setVisible(true);
    }//GEN-LAST:event_tbSupplierMousePressed

    private void menuUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateActionPerformed
        if(jTabbedPane1.getSelectedIndex() == 0){
            Supplier sup = new Supplier();
            sup.setId_supplier(tbSupplier.getModel().getValueAt(tbSupplier.getSelectedRow(), 0).toString());
            FormSupplier fIS = new FormSupplier(supDAO, sup.getId_supplier(), this);
            fIS.setTitle("Update Supplier");
            fIS.setVisible(true);
            fIS.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else if(jTabbedPane1.getSelectedIndex() == 1){
            Sepatu spt = new Sepatu();
            Sepatu_Supplier ss = ssDAO.GetSupplier(tbSepatu.getModel().getValueAt(tbSepatu.getSelectedRow(), 0).toString());
            FormSepatu fES = new FormSepatu(supDAO, sptDAO, ss.getId_supplier(), 
                    tbSepatu.getModel().getValueAt(tbSepatu.getSelectedRow(), 0).toString(), this);
            fES.setTitle("Update Sepatu");
            fES.setVisible(true);
            fES.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_menuUpdateActionPerformed

    private void menuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeleteActionPerformed
        if(jTabbedPane1.getSelectedIndex() == 0){
            Supplier sup = new Supplier();
            sup.setId_supplier(tbSupplier.getModel().getValueAt(tbSupplier.getSelectedRow(), 0).toString());
            supDAO.Delete(sup);
            //====Delete_sepatu_table==============
            List<Sepatu_Supplier> ProductList =
                ssDAO.GetAllSepatuBySupplier(tbSupplier.getModel().getValueAt(tbSupplier.getSelectedRow(), 0).toString());
             for(Sepatu_Supplier sp:ProductList){
                 sptDAO.Delete(sptDAO.GetSepatu(sp.getId_sepatu()));
             }
            //====Delete_sepatu_table==============
            ssDAO.DeleteSupplier(sup);
            LihatDataSupplier();
            LihatDataSepatu();
        } else if(jTabbedPane1.getSelectedIndex() == 1){
            Sepatu spt = new Sepatu();
            spt.setId_sepatu(tbSepatu.getModel().getValueAt(tbSepatu.getSelectedRow(), 0).toString());
            sptDAO.Delete(spt);
            ssDAO.DeleteSepatu(spt);
            LihatDataSepatu();
        }
    }//GEN-LAST:event_menuDeleteActionPerformed

    private void menuProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductActionPerformed
        lbSupplier.setText(tbSupplier.getModel().getValueAt(tbSupplier.getSelectedRow(), 1).toString());
        jTabbedPane1.add(productPanel);
        jTabbedPane1.setTitleAt(2, "Supplier Product");
        jTabbedPane1.setSelectedComponent(productPanel);
        
        List<Sepatu_Supplier> ProductList =
                ssDAO.GetAllSepatuBySupplier(tbSupplier.getModel().getValueAt(tbSupplier.getSelectedRow(), 0).toString());
        Object[][] dataSupplierProduct = new Object[
                ProductList.size()][2];
        int i = 0;
        for(Sepatu_Supplier sp:ProductList){
            dataSupplierProduct[i][0] = sp.getId_sepatu();
            dataSupplierProduct[i][1] = sptDAO.GetSepatu(sp.getId_sepatu()).getNama_sepatu();
            i++;
        }
        tbProduct.setModel(new DefaultTableModel(dataSupplierProduct, new String[]{"ID", "Nama Sepatu"}));
    }//GEN-LAST:event_menuProductActionPerformed

    private void menuAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddProductActionPerformed
        FormSepatu fES = new FormSepatu(supDAO, sptDAO, 
                tbSupplier.getModel().getValueAt(tbSupplier.getSelectedRow(), 0).toString()
                , "", this);
        fES.setTitle("Add Product");
        fES.setVisible(true);
        fES.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuAddProductActionPerformed

    private void tbSepatuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSepatuMousePressed
        if(tbSepatu.getSelectedRowCount() > 0){
            menuUpdate.setEnabled(true);
            menuDelete.setEnabled(true);
        } else{
            menuUpdate.setEnabled(false);
            menuDelete.setEnabled(false);
        }
        menuProduct.setVisible(false);
        menuAddProduct.setVisible(false);
    }//GEN-LAST:event_tbSepatuMousePressed

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        if(jTabbedPane1.getSelectedIndex() == 0 || jTabbedPane1.getSelectedIndex() == 1){
            jTabbedPane1.remove(jPanel3);
        }
    }//GEN-LAST:event_jTabbedPane1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTokoSepatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTokoSepatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTokoSepatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTokoSepatu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTokoSepatu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSepatuLihat;
    private javax.swing.JButton btnSupplierInsert;
    private javax.swing.JButton btnSupplierLihat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbSupplier;
    private javax.swing.JMenuItem menuAddProduct;
    private javax.swing.JMenuItem menuDelete;
    private javax.swing.JMenuItem menuProduct;
    private javax.swing.JMenuItem menuUpdate;
    private javax.swing.JPopupMenu popupTable;
    private javax.swing.JTable tbProduct;
    private javax.swing.JTable tbSepatu;
    private javax.swing.JTable tbSupplier;
    // End of variables declaration//GEN-END:variables
}
